#logging:
#  level:
#    org:
#      springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '!Ohmygod123'
    url: jdbc:mysql://localhost:3306/whats_next
    username: zkhuang
  jpa:
    hibernate:
      ddl-auto: update
